### ISSUE TITLE
[bug-website module] ManhwaFreak not able to download manga list from server

### ISSUE THREAD

**Issue by acg5159** [dazedcat19/FMD#1364]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 22H2 x64

### Describe the bug

When selecting "Download manga list from server" for ManhwaFreak I get the 404 Error. I am able to get to the website fine https://manhwa-freak.com/ (though I noticed the name changed to include a '-' not sure if related).

**Comment by acg5159** [comment]
this may not be the same group as before: https://github.com/dazedcat19/FMD2/issues/1326
If it is not the same, can we add it?

**Comment by jpwong2** [comment]
It seems to be the same group as in 1326, however freakcomic seems to be an incomplete backup site or something because it's missing most of the group's series, and what is up there says for latest updates, read on manhwa-freak.com so they may have intended to use it as a fallback since a lot of other groups also picked "comic" site URLs when they had to move.

**Comment by Slasar41** [comment]
So which one is the main site, manhwa-freak.com or freakcomic.com?
Accessing the old URL "manhwafreak.com" redirect to "manhwa-freak.com".

**Comment by jpwong2** [comment]
Everything indicates that https://manhwa-freak.com/ is their main site right now, I think the other one is a backup or something in case they have to move again.
