### ISSUE TITLE
[bug-website module] rizzcomic.com changes to rizzfables.com

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#1460]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

https://rizzcomic.com/ changes to https://rizzfables.com/
and so all the sub webpages
https://rizzfables.com/series

**Comment by Qizmo** [comment]
I change my .lua to  https://rizzfables.com/ already.
At first it is working fine and can load normally. However today I keep getting error. When I try looking at the manga from the website itself, when you try looking into any manga's chapter for the first time it will need to be verified first, after that no more verified page appeared. Maybe due to this, so can't download any more manga from here.

PS. My problem is fixed now. The manga can be loaded normally again ^^

**Comment by hesoyamma785** [comment]
> I change my .lua to https://rizzfables.com/ already. At first it is working fine and can load normally. However today I keep getting error. When I try looking at the manga from the website itself, when you try looking into any manga's chapter for the first time it will need to be verified first, after that no more verified page appeared. Maybe due to this, so can't download any more manga from here.
> 
> PS. My problem is fixed now. The manga can be loaded normally again ^^

which .lua file did you change?

**Comment by Souravi785** [comment]
@Qizmo how did you fix it?

**Comment by jpwong2** [comment]
> @Qizmo how did you fix it?

Go to the lua\modules directory, open the RizzComics.lua in a text editor and change the address next to the m.RootURL value.  Save.  Restart FMD.

**Comment by Souravi785** [comment]
It's working but now the speed is too slow.

**Comment by alyyyya** [comment]
@Souravi785 怎么弄看不懂啊？
