### ISSUE TITLE
[bug-website module] hiperdex changes to hipertoon

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1776]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

hiperdex changes to hipertoon.com
sometimes when they change to other domain or site, we can still using the old name phrase.
for ex, komikindo right now change domain from .lol to .my
but just change the name fmd can capture it. bcs still bring the same access.
on hiperdex sometimes we can do that as well, but on this case change the name didn't work to bypass it

**Comment by kayhos** [comment]
I confirm the same URL structure is kept under hipertoon.com Not having to replace all the favorites because of this change would be great.

For information, 

In the file **lua/modules/Hiperdex.lua**, replacing the value of ```m.RootURL``` from `https://hiperdex.com` to `https://hipertoon.com` seems to fix it. Your milleage may vary :

End result should look like this:
```
function Init()
	local m = NewWebsiteModule()
	m.ID                       = '2b5f00cfbb124546b6c11a7e5ec9c403'
	m.Name                     = 'Hiperdex'
	m.RootURL                  = 'https://hipertoon.com'
	m.Category                 = 'H-Sites'
	m.OnGetNameAndLink         = 'GetNameAndLink'
	m.OnGetInfo                = 'GetInfo'
	m.OnGetPageNumber          = 'GetPageNumber'
end
```
