### ISSUE TITLE
[bug] cannot be downloaded from welovemanga

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD#728]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 7 ULTIMATE

**Describe the bug**
It has not allowed to download from the page .. I have tried several titles and none works

**Screenshots**
![image](https://user-images.githubusercontent.com/53473707/133678588-92dc567e-d20b-4149-97cd-26d76ffc0b59.png)

**Additional context**
those titles that appear in the show are from my favorites list

**Comment by Trollam** [comment]
They have a redirection in place when we try to get the images without the right header.

Edit: They have activated a DDOS protection, it's not cloudflare.

I was trying to get the images, this instructions can get the links but I'm stuck on the DDOS protection:
``` '//img[contains(@class, "chapter-img")]/@*[contains(., "ihlv1.xyz")])' ```

**Comment by TienVer** [comment]
For two days now the favorites page only successfully pings a very small fraction of all my WeLoveManga entries. One in twenty or thereabouts - the rest gets zeroed out. Please note that FMD2 is **still** able to download chapters, even the ones locked behind the age gate, so it's not a login issue.

![Untitled-3](https://user-images.githubusercontent.com/62098226/135418050-8e7296a0-1234-4b56-8761-9cb6046bc806.jpg)

I suppose this is due to the website's DDOS protection blocking most of the rapid-fire data requests from FMD2 and only letting through a mere handful?

EDIT: right-clicking each entry separately and selecting "check for new chapter" does work, but it's tedious if you have a long list of favorites. I also can't do it too quickly or I end up tripping the DDOS barrier. :-/

**Comment by Slasar41** [comment]
Do cookies workaround and decrease the connection number in FMD options.

**Comment by TienVer** [comment]
Cookies workaround wasn't much help; it was much easier monitoring the website and do an individual check of my updated favorites. A bit of a nuisance, but I could still work with that.

Speaking of which...couldn't download anything from WLM this morning. The update checks do not pass and right-click->"view manga info" yields the error message "Cannot get manga info. Please check your internet connection and try it again". Tried updating the cookie parameters to no avail; no joy after setting the option on and off, either.

**Comment by Slasar41** [comment]
Workaround and downloading is still working on my end.
