### ISSUE TITLE
[bug-website module] download failed manhwa18.com and manhwa18.net

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD#742]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 x64 latest update

### Describe the bug

Download failed from manhwa18 sites, I can check the website from browser normally. I tried using cloudfare workaround and not, using VPN and not. All of them are the same, can check manga from FMD but failed at download. I dont know exactly when the problems 1st occurs since I only have 4 manhwas from manhwa18, but I have this problem yesterday when a manh
wa got an update.

![sssssss](https://user-images.githubusercontent.com/26659986/134600049-22c6d975-c1bb-4dbb-a67e-09e6f864a499.png)

**Comment by otakuakiba** [comment]
yeah, its happen to me too. just recently, since i can download from there 2-3 days ago. seems like the script for image source/repository changed, but the program can parse the chapter list just fine.
anyway can i ask you what do you mean by "cloudfare workaround"?
i tried to find program to bypass cloudflare in the past but found no result, mostly just script that need phython(and the likes) to execute.
thanks in advance.

**Comment by Plegmatis** [comment]
@otakuakiba you can try this https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964

**Comment by otakuakiba** [comment]
@Plegmatis thanks bro.
