### ISSUE TITLE
[bug] Weloma and WeLoveManga

### ISSUE THREAD

**Issue by EPP9849** [dazedcat19/FMD#761]
**Prerequisite**
- [ ] I'm using the latest version.
- [ ] All website modules are up to date.

- [ ] This is not temporary server issue.

**System information**
Your operating system.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

I simply cannot download from Weloma (404 not found) and WeLoveManga (Manga list shows up, and immediately disappeared once double clicked), I tried to access those 2 websites via browser and it works normally. I used to downlad from LoveHug, but I cannot download from it anymore

**Comment by Slasar41** [comment]
Do cookies workaround and copy the link of manga from browser to FMD.

**Comment by TienVer** [comment]
The latest lhscan module update restored the ability to see chapters in the series page as well as register favorite updates from WLM, but downloads still fail.

Additionally, I noticed that my WeLoveManga account status in the settings now reads as "**Unknown**". I just double-checked on several browsers and my login and password are both okay (although, strangely enough, WLM's login form seems to ignore the letter "i", both upper- and lowercase, and in both the login and password fields).

![Untitled-2](https://user-images.githubusercontent.com/62098226/138568345-fe32b8fc-ed32-44d9-a1e3-f9328b5bfd68.jpg)

As for the cookie workaround...which parameters do we need exactly, just to be clear? I currently have **userId**, **userName**, **PHPSESSID** and **hash** concatenated in the string (which has worked for the longest time in that form without other additions, until WLM started to dabble in this anti-DDOS mess), and dutifully entered my browser's current user agent in the field just below, but no joy. Also, every couple of days the website seems to introduce some new anti-DDOS mechanism and a handful of new cookie values ("antibot_****"). In the browser, this protection translates to a page where we have to select the appropriate color in order to be let through.

EDIT: never mind. For some reason it's working again. No clue why.

**Comment by TienVer** [comment]
...Aaaand the WLM plugin needs to be updated again. Account settings are okay, but I cannot pull up profile pages for any series.

**Comment by Slasar41** [comment]
@TienVer It doesn't matter if you logged in your account in FMD or not, you still need to do cookies workaround because the website has captcha.
Just tested and download is still working fine on my end.
